development:
  adapter: postgresql
  encoding: unicode
  database: rails-opt_development
  pool: 5
  username: wdi
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: rails-opt_development
  pool: 5
  username: wdi
  password:
